project:
  type: book
  output-dir: ../docs

book:
  title: "book"
  author: "Jane Doe"
  date: "23-2-2023"
  chapters:
    - index.qmd
    - intro.qmd
    - test.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt



