project:
  type: book
  output-dir: ../docs

book:
  title: "Introduction to Python & Data"
  author: "Research Data Management Support"
  date: "02-03-2023"
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - schedule.qmd
    - installation-and-setup.qmd
    - course-materials.qmd
    - introduction.qmd
    - python-101.ipynb
    - data-science-with-pandas.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt



