on:
  push:
    branches: main
    paths:
      - 'course_materials/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Zip Course materials
      run: zip -r course_materials.zip course_materials